language: objective-c

notifications:
 email: false

xcode_workspace: Urchin.xcworkspace
xcode_scheme: Urchin
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

before_install:
- git submodule update --init --recursive

script:
- xctool test -workspace Urchin.xcworkspace -scheme Urchin -sdk iphonesimulator clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
